spring:
  application:
    name: shoppingmall

---

spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/shoppingmall
    username: ${DB_USER}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        connection:
          CharSet: utf-8
          characterEncoding: utf-8
          useUnicode: true

logging.level:
  root: info

jwt:
  secret-key: ${JWT-SECRET-KEY}
