spring:
  application:
    name: shoppingmall

---
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        connection:
          CharSet: utf-8
          characterEncoding: utf-8
          useUnicode: true
        dialect: org.hibernate.dialect.MySQLDialect

logging.level:
  root: info

jwt:
  secret-key: ${JWT-SECRET-KEY}
